with Ada.Text_IO;
with Ada.Strings.Fixed;

procedure Bitmaps.Put_Image (Bitmap : Bitmap_Header) is
   use Ada.Text_IO;
   use Ada.Strings.Fixed;
   package Unsigned_32_Text_IO is new Modular_IO (Unsigned_32);
   package Unsigned_16_Text_IO is new Modular_IO (Unsigned_16);
   use Unsigned_32_Text_IO;
   use Unsigned_16_Text_IO;
   Column_1_Width : constant := 25;
   Column_2_Width : constant := 20;
begin
   Put (Head("Signature", Column_1_Width));
   Put (Tail(Bitmap.File.Sign'Img, Column_2_Width));
   New_Line;
   Put (Head("Size ", Column_1_Width));
   Put (Bitmap.File.Size, Column_2_Width);
   New_Line;
   Put (Head("Reserved_1", Column_1_Width));
   Put (Bitmap.File.Reserved_1, Column_2_Width);
   New_Line;
   Put (Head("Reserved_1", Column_1_Width));
   Put (Bitmap.File.Reserved_1, Column_2_Width);
   New_Line;
   Put (Head("Offset", Column_1_Width));
   Put (Bitmap.File.Offset, Column_2_Width);
   New_Line;
   Put (Head("Header_Size", Column_1_Width));
   Put (Bitmap.Information.Header_Size, Column_2_Width);
   New_Line;
   Put (Head("Width", Column_1_Width));
   Put (Bitmap.Information.Width, Column_2_Width);
   New_Line;
   Put (Head("Height", Column_1_Width));
   Put (Bitmap.Information.Height, Column_2_Width);
   New_Line;
   Put (Head("Plane_Count", Column_1_Width));
   Put (Bitmap.Information.Plane_Count, Column_2_Width);
   New_Line;
   Put (Head("Pixel_Size", Column_1_Width));
   Put (Bitmap.Information.Pixel_Size, Column_2_Width);
   New_Line;
   Put (Head("Compression", Column_1_Width));
   Put (Tail(Bitmap.Information.Compress'Img, Column_2_Width));
   New_Line;
   Put (Head("Image_Size", Column_1_Width));
   Put (Bitmap.Information.Image_Size, Column_2_Width);
   New_Line;
   Put (Head("Horizontal_Resolution", Column_1_Width));
   Put (Bitmap.Information.Horizontal_Resolution, Column_2_Width);
   New_Line;
   Put (Head("Vertical_Resolution", Column_1_Width));
   Put (Bitmap.Information.Vertical_Resolution, Column_2_Width);
   New_Line;
   Put (Head("Color_Count", Column_1_Width));
   Put (Bitmap.Information.Color_Count, Column_2_Width);
   New_Line;
   Put (Head("Important_Color_Count", Column_1_Width));
   Put (Bitmap.Information.Important_Color_Count, Column_2_Width);
   New_Line;
end;
